signing_key: 4A424030614ADE118389C2FD27BDB3E5F0331921.pub
baseurl: /spack-build-cache
repository: 
title: Spack Build Cache
description: A GitHub-based build cache for spack, with a nice UI to boot.
url: ""

# Change if you deploy to a root, or another docs subfolder
subfolder: "docs"

paginate: 28

banner: "/assets/img/banner.png" # site banner (load when someone share your page url)
favicon: "/assets/img/favicon.ico" # site's favicon (icon left side of your page)

# Collections
collections:
  cache:
    output: true
    permalink: /:collection/:path

defaults:
  - scope:
      path: "_cache"
      type: "cache"
    values:
      layout: "cache"

user: 
  avatar: "/assets/img/logo.png"
  github: "vsoch"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title

plugins:
  - jekyll-scholar
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-redirect-from
  - github-pages

exclude:
  - Gemfile
  - Gemfile.lock
